(function(g){var window=this;var aEa=function(a,b){return g.ec(a,b)},c6=function(a){g.ln(a,"zx",g.Eb());
return a},d6=function(a,b,c){g.Fa(c)||(c=[String(c)]);
g.on(a.o,b,c)},bEa=function(a,b){var c=[];
g.Xk(b,function(a){try{var b=g.LD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.za(b)?g.KD(b)&&c.push(a):c.push(a)},a);
return c},cEa=function(a,b){var c=bEa(a,b);
(0,g.C)(c,function(a){g.LD.prototype.remove.call(this,a)},a)},dEa=function(a){if(a.Sd){if(a.Sd.locationOverrideToken)return{locationOverrideToken:a.Sd.locationOverrideToken};
if(null!=a.Sd.latitudeE7&&null!=a.Sd.longitudeE7)return{latitudeE7:a.Sd.latitudeE7,longitudeE7:a.Sd.longitudeE7}}return null},eEa=function(a,b,c,d){var e=new g.bn(null,void 0);
a&&g.cn(e,a);b&&g.dn(e,b);c&&g.en(e,c);d&&g.fn(e,d);return e},e6=function(a,b){g.DE[a]=!0;
var c=g.BE();c&&c.publish.apply(c,arguments);g.DE[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Wm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",fEa(this,a.capabilities||""),gEa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},fEa=function(a,b){a.capabilities.clear();
(0,g.fe)(b.split(","),g.La(aEa,hEa)).forEach(function(b){a.capabilities.add(b)})},gEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},iEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},jEa=function(a){return new g6(a)},kEa=function(a){return g.Fa(a)?(0,g.I)(a,jEa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.Fa(a)?"["+(0,g.I)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},lEa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},l6=function(a,b){return g.Qa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},m6=function(a,b){return g.Qa(a,function(a){return h6(a,b)})},mEa=function(){var a=(0,g.NH)();
a&&cEa(a,a.o.ke(!0))},n6=function(){var a=g.QH("yt-remote-connected-devices")||[];
g.pb(a);return a},nEa=function(a){if(g.Va(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},oEa=function(a){g.PH("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.QH("yt-remote-device-id");a||(a=k6(),g.PH("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.Ua(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.Ua(a,b);g.SH()&&g.rb(a,b);a=nEa(a);if(g.Va(a))try{g.mH("remote_sid")}catch(c){}else try{g.lH("remote_sid",a.join(","),-1)}catch(c){}},pEa=function(){return g.QH("yt-remote-session-browser-channel")},qEa=function(){return g.QH("yt-remote-local-screens")||[]},rEa=function(){g.PH("yt-remote-lounge-token-expiration",!0,86400)},sEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(qEa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.Km)(c,function(a){return!g.Ua(b,a)})&&rEa();
g.PH("yt-remote-local-screens",a,31536E3)},tEa=function(a,b){g.PH("yt-remote-session-browser-channel",a);
g.PH("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.Ua(c,d)||c.push(d);oEa(c);q6()},r6=function(a){a||(g.RH("yt-remote-session-screen-id"),g.RH("yt-remote-session-video-id"));
q6();a=n6();g.Za(a,p6());oEa(a)},uEa=function(){if(!s6){var a=g.WD();
a&&(s6=new g.FD(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},t6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},vEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?wEa(a.shift(),function(){u6(a)}):v6()},xEa=function(a){return"chrome-extension://"+a+w6},wEa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=vEa();
a&&a(!1,"No cast extension found")},zEa=function(){if(yEa){var a=2,b=vEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;wEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},AEa=function(){zEa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+w6,"//www.gstatic.com/eureka/clank"+w6])},x6=function(a,b,c){g.J.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.Ld=b;this.D=(0,g.A)(this.gM,this);this.o=!1;this.A=0;this.B=this.Ia=null;this.C=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.sn(this);this.A=new g.Hg;this.A.setInterval(250)},CEa=function(a,b,c){a.jk=1;
a.Rh=c6(b.clone());a.yj=c;a.D=!0;BEa(a,null)},A6=function(a,b,c,d,e){a.jk=1;
a.Rh=c6(b.clone());a.yj=null;a.D=c;e&&(a.TG=!1);BEa(a,d)},BEa=function(a,b){a.ll=(0,g.H)();
B6(a);a.wi=a.Rh.clone();d6(a.wi,"t",a.F);a.xo=0;a.bd=a.o.qu(a.o.oo()?b:null);0<a.Xu&&(a.Cr=new g.Fl((0,g.A)(a.gI,a,a.bd),a.Xu));a.Y.X(a.bd,"readystatechange",a.rX);var c=a.Yi?g.mc(a.Yi):{};a.yj?(a.Es="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.bd.send(a.wi,a.Es,a.yj,c)):(a.Es="GET",a.TG&&!g.Ud&&(c.Connection="close"),a.bd.send(a.wi,a.Es,null,c));a.o.Mf(1)},FEa=function(a,b,c){for(var d=!0;!a.Ii&&a.xo<c.length;){var e=DEa(a,c);
if(e==C6){4==b&&(a.Sh=4,D6(15),d=!1);break}else if(e==EEa){a.Sh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Sh=1,D6(17),d=!1);a.Sf=a.Sf&&d;d||(F6(a),G6(a))},DEa=function(a,b){var c=a.xo,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return EEa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.xo=d+c;return e},HEa=function(a,b){a.ll=(0,g.H)();
B6(a);var c=b?window.location.hostname:"";a.wi=a.Rh.clone();g.ln(a.wi,"DOMAIN",c);g.ln(a.wi,"t",a.F);try{a.Uf=new ActiveXObject("htmlfile")}catch(n){F6(a);a.Sh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in GEa)k=H6[l]=GEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.xd(g.Lc("b/12014412"),d+"</body></html>");a.Uf.open();a.Uf.write(g.ld(c));a.Uf.close();a.Uf.parentWindow.m=(0,g.A)(a.xW,a);a.Uf.parentWindow.d=(0,g.A)(a.dG,a,!0);a.Uf.parentWindow.rpcClose=(0,g.A)(a.dG,a,!1);c=a.Uf.createElement("DIV");a.Uf.parentWindow.document.body.appendChild(c);d=g.Zc(a.wi.toString());d=g.yb(g.Wc(d));d=g.xd(g.Lc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.rd(c,g.ld(d));a.o.Mf(1)},B6=function(a){a.bz=(0,g.H)()+
a.C;
IEa(a,a.C)},IEa=function(a,b){if(null!=a.Hl)throw Error("WatchDog timer not null");
a.Hl=I6((0,g.A)(a.NW,a),b)},J6=function(a){a.Hl&&(g.v.clearTimeout(a.Hl),a.Hl=null)},G6=function(a){a.o.xC()||a.Ii||a.o.fr(a)},F6=function(a){J6(a);
g.tf(a.Cr);a.Cr=null;a.A.stop();g.yn(a.Y);if(a.bd){var b=a.bd;a.bd=null;b.abort();b.dispose()}a.Uf&&(a.Uf=null)},E6=function(a,b){try{a.o.WF(a,b),a.o.Mf(4)}catch(c){}},KEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;JEa(a,b,function(e){e?c(!0):g.v.setTimeout(function(){KEa(a,b,c,d,f)},f)})}},JEa=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},LEa=function(a){this.o=a;
this.A=new y6},MEa=function(a){var b=L6(a.o,a.Zl,"/mail/images/cleardot.gif");
c6(b);KEa(b.toString(),5E3,(0,g.A)(a.hL,a),3,2E3);a.Mf(1)},N6=function(a){var b=a.o.J;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.Re=new z6(a,void 0,void 0,void 0),a.Re.Yi=a.Vu,b=a.o,b=L6(b,b.oo()?a.Tm:null,a.Wu),D6(5),!g.Sd||g.Dc(10))d6(b,"TYPE","xmlhttp"),A6(a.Re,b,!1,a.Tm,!1);else{d6(b,"TYPE","html");var c=a.Re;a=!!a.Tm;c.jk=3;c.Rh=c6(b.clone());HEa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new y6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},NEa=function(a,b){this.o=a;
this.map=b;this.context=null},OEa=function(a){g.vf.call(this,"statevent",a)},PEa=function(a,b){g.vf.call(this,"timingevent",a);
this.size=b},QEa=function(a){g.vf.call(this,"serverreachability",a)},TEa=function(a){REa(a);
if(3==a.o){var b=a.Tn++,c=a.Fp.clone();g.ln(c,"SID",a.B);g.ln(c,"RID",b);g.ln(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.B,b,void 0);b.jk=2;b.Rh=c6(c.clone());(new Image).src=b.Rh;b.ll=(0,g.H)();B6(b)}SEa(a)},UEa=function(a){a.FL(1,0);
a.Fp=L6(a,null,a.Uu);Q6(a)},REa=function(a){a.Fh&&(a.Fh.abort(),a.Fh=null);
a.Ec&&(a.Ec.cancel(),a.Ec=null);a.Sg&&(g.v.clearTimeout(a.Sg),a.Sg=null);R6(a);a.se&&(a.se.cancel(),a.se=null);a.Lh&&(g.v.clearTimeout(a.Lh),a.Lh=null)},VEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new NEa(a.lS++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.se||a.Lh||(a.Lh=I6((0,g.A)(a.cG,a),0),a.bk=0)},XEa=function(a,b){if(1==a.o){if(!b){a.Tn=Math.floor(1E5*Math.random());
var c=a.Tn++,d=new z6(a,"",c,void 0);d.Yi=null;var e=S6(a),f=a.Fp.clone();g.ln(f,"RID",c);g.ln(f,"CVER","1");P6(a,f);CEa(d,f,e);a.se=d;a.o=2}}else 3==a.o&&(b?WEa(a,b):0==a.A.length||a.se||WEa(a))},WEa=function(a,b){if(b)if(6<a.Li){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Tn-1;var d=S6(a)}else c=b.G,d=b.yj;else c=a.Tn++,d=S6(a);var e=a.Fp.clone();g.ln(e,"SID",a.B);g.ln(e,"RID",c);g.ln(e,"AID",a.Fk);P6(a,e);c=new z6(a,a.B,c,a.bk+1);c.Yi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.se=c;CEa(c,e,d)},P6=function(a,b){if(a.Kd){var c=a.Kd.cC();
c&&g.Rb(c,function(a,c){g.ln(b,c,a)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.Li&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.Li?e:f-d;try{g.Rb(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},YEa=function(a){a.Ec||a.Sg||(a.G=1,a.Sg=I6((0,g.A)(a.bG,a),0),a.Tj=0)},T6=function(a){if(a.Ec||a.Sg||3<=a.Tj)return!1;
a.G++;a.Sg=I6((0,g.A)(a.bG,a),ZEa(a,a.Tj));a.Tj++;return!0},M6=function(a,b,c){a.Bs=c;
a.gg=b.ih;a.F||UEa(a)},R6=function(a){null!=a.Ni&&(g.v.clearTimeout(a.Ni),a.Ni=null)},ZEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Kd&&(c=null);var d=(0,g.A)(a.kY,a);c||(c=new g.bn("//www.google.com/images/cleardot.gif"),c6(c));JEa(c.toString(),1E4,d)}else D6(2);$Ea(a,b)},$Ea=function(a,b){a.o=0;
a.Kd&&a.Kd.bB(b);SEa(a);REa(a)},SEa=function(a){a.o=0;
a.gg=-1;if(a.Kd)if(0==a.C.length&&0==a.A.length)a.Kd.cu();else{g.cb(a.C);var b=g.cb(a.A);a.C.length=0;a.A.length=0;a.Kd.cu(b)}},L6=function(a,b,c){var d=g.mn(c);
if(""!=d.A)b&&g.dn(d,b+"."+d.A),g.en(d,d.D);else{var e=window.location;d=eEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.ym&&g.Rb(a.ym,function(a,b){g.ln(d,b,a)});
g.ln(d,"VER",a.Li);P6(a,d);return d},I6=function(a,b){if(!g.Ha(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new OEa(V6,a))},aFa=function(){},bFa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.J.call(this);
this.o=new g.U(this.nW,0,this);g.K(this,this.o);this.Ld=5E3;this.A=0;if(g.Ha(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ha(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},X6=function(a,b,c){this.K=a;
this.F=b;this.B=new g.ED;this.A=new W6(this.NY,this);this.o=this.qb=null;this.Eb=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.L=c||!1},cFa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Bs,sessionId:a.o.B,arrayId:a.o.Fk}},dFa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&XEa(a.o),TEa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},eFa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||document.location.href;var b=g.Wg(a)||"";b&&(this.port=":"+b);this.domain=g.Vg(a)||"";a=g.Pb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.za(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.eh(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.La(a.C,d,!0),onError:g.La(a.B,e),Pd:g.La(a.D,e)};c&&(a.Tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.jF(b,a)},iFa=function(){var a=fFa;
gFa();b7.push(a);hFa(b7)},c7=function(a,b){gFa();
var c=b7,d=jFa(a,String(b));g.Va(c)?kFa(d):(hFa(c),(0,g.C)(c,function(a){a(d)}))},gFa=function(){b7||(b7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ca("yt.mdx.remote.debug.handlers_",b7,void 0))},kFa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},hFa=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},jFa=function(a,b){var c=((0,g.H)()-lFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.V.call(this);
this.G=a;this.o=[]},mFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},nFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.fe)(a.o,function(a){return!!l6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=mFa(a,b[d])||c;return c},oFa=function(a,b){var c=a.o.length;
a.o=(0,g.fe)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.V.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ia=NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.B=a;this.A=NaN;i7(this);this.info("Initializing with "+j6(this.o))},pFa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=$6(a.B,"/pairing/get_lounge_token_batch");
a7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.uM,a),(0,g.A)(a.tM,a))}},i7=function(a){var b=kEa(qEa());
b=(0,g.fe)(b,function(a){return!a.uuid});
return nFa(a,b)},k7=function(a,b){sEa((0,g.I)(a.o,iEa));
b&&rEa()},m7=function(a,b){g.V.call(this);
this.F=b;var c=g.QH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ua(c,l)}this.o=d;this.D=a;this.B=this.C=NaN;this.A=null;l7("Initialized with "+g.Ng(this.o))},qFa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Wb(b)!=g.Wb(a.o))var c=!1;
else{c=g.bc(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.Ng(a.o)),a.o=b,a.V("screenChange"));rFa(a)},o7=function(a){isNaN(a.B)||g.AE(a.B);
a.B=g.yE((0,g.A)(a.Xx,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},sFa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.yc("Requesting availability of screen w/o lounge token.")});
return b},rFa=function(a){a=g.bc(g.Sb(a.o,function(a){return a}));
g.pb(a);a.length?g.PH("yt-remote-online-screen-ids",a.join(","),60):g.RH("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};tFa(this)},vFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Ke();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=q7(a,k);qFa(a.A,l,function(a){e(a?l:null)})}else c?uFa(a,c,(0,g.A)(function(a){var f=q7(this,new g6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));qFa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},wFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},uFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.jF($6(a.F,"/pairing/get_lounge_token_batch"),e)},xFa=function(a){a.o=a.B.Ke();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.o))},tFa=function(a){r7(a);
a.B=new j7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.HM,a));xFa(a);a.C=kEa(g.QH("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+j6(a.C));a.A=new m7(a.F,(0,g.A)(a.Ke,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.PH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,iEa)));r7(a);a.D[b.uuid]=b.id;g.PH("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.QH("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.V.call(this);
this.R=c;this.J=a;this.A=b;this.B=null},t7=function(a,b){c7(a.R,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.TY,this);this.D=(0,g.A)(this.ZW,this);this.C=g.yE((0,g.A)(function(){yFa(this,null)},this),12E4)},zFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ng(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.Ng(b))},yFa=function(a,b){g.AE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.gr,a),d=(0,g.A)(a.Qe,a);a.nC(b,c,d,5)}}else a.Qe(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.N=c;this.D=null;this.G=g.z;this.F=NaN;this.L=(0,g.A)(this.WY,this);this.o=g.z},AFa=function(a){a.o=a.J.mI(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.gr(a)},a),(0,g.A)(function(a){this.o=g.z;
this.Qe(a)},a))},BFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.N;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}uEa()&&(b.env_useStageMdx=1);return g.ch(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.yE((0,g.A)(this.Hk,this,null),150)},x7=function(a,b,c,d){g.V.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.yV,this)},CFa=function(a,b){return b?g.Qa(a.B,function(a){return h6(b,a.label)},a):null},y7=function(a){c7("Controller",a)},fFa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.B.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.tf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.ZF,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.Hk(null)):a.V("yt-remote-cast2-session-change",null))},DFa=function(a){var b=a.A.lI(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&h6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=CFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},JFa=function(a,b,c,d,e,f,k){EFa()?FFa(b,e,f,k)&&(C7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?GFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?GFa(a,c):(D7("Failed to load cast API: "+d),E7(!1),C7(!1),g.RH("yt-remote-cast-available"),g.RH("yt-remote-cast-receiver"),HFa(),c(!1))},d?g.LE("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?AEa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(zEa(),u6(IFa.map(xEa))))):B7("Cannot initialize because not running Chrome")},HFa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.Ca("yt.mdx.remote.cloudview.instance_",null,void 0);KFa(!1);g.GE(G7);G7.length=0},H7=function(){return!!g.QH("yt-remote-cast-installed")},LFa=function(){var a=g.QH("yt-remote-cast-receiver");
return a?a.friendlyName:null},MFa=function(){B7("clearCurrentReceiver");
g.RH("yt-remote-cast-receiver")},NFa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.FE("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},EFa=function(){var a=0<=g.Pb.search(/ (CrMo|Chrome|CriOS)\//);
return g.nL||a},OFa=function(a,b){F7().init(a,b)},FFa=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.PH("yt-remote-cast-available",a);e6("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){B7("onReceiverSelected: "+a.friendlyName);
g.PH("yt-remote-cast-receiver",a);e6("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){B7("onReceiverResumed: "+a.friendlyName);
g.PH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){B7("onSessionChange: "+i6(a));
a||g.RH("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",a)}),g.Ca("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},GFa=function(a,b){E7(!0);
C7(!1);OFa(a,function(a){a?(KFa(!0),g.IE("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.RH("yt-remote-cast-available"),g.RH("yt-remote-cast-receiver"),HFa());b(a)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.PH("yt-remote-cast-installed",a)},I7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},KFa=function(a){B7("setApiReady_ "+a);
g.Ca("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.Ca("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.kg=!1;this.J=this.H=this.A=this.C=0;this.B=NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.kg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.C=0;a.A=0;a.H=0;a.J=0;a.B=NaN;a.D=!1},N7=function(a){return a.vb()?((0,g.H)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.H)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.nc(a.o);b.hasPrevious=a.kg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},T7=function(a,b){g.V.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.VC;this.B=this.A=null;this.J=(0,g.A)(this.XS,this);this.G=(0,g.A)(this.Wn,this);this.H=(0,g.A)(this.WS,this);this.K=(0,g.A)(this.jT,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.xz,this),PFa(this))):c=3;0!=c&&(b?this.xz(c):g.yE((0,g.A)(function(){this.xz(c)},this),0));
var d=NFa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.C.getPlayerContextData())},PFa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.La(this.uV,a),this))},a)},QFa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},V7=function(a,b){50>a.D.Pc()&&g.XC(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.C.sendMessage(b,c)},W7=function(a,b){QFa(a);
a.C.setPlayerContextData(R7(b));PFa(a)},S7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Wn(null));
a.B=b;a.B&&(c7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Wn(a.B.media[0]))},RFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.A)(function(a){this.yc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.yc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.V.call(this);
this.D=NaN;this.N=!1;this.K=this.J=this.L=this.R=NaN;this.T=[];this.C=this.G=this.B=this.rb=this.o=null;this.sa=a;this.T.push(g.lG(window,"beforeunload",(0,g.A)(this.kM,this)));this.A=[];this.rb=new L7;this.aa=b.id;this.o=SFa(this,c);this.o.subscribe("handlerOpened",this.bT,this);this.o.subscribe("handlerClosed",this.YS,this);this.o.subscribe("handlerError",this.ZS,this);this.o.subscribe("handlerMessage",this.aT,this);eFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=this.rb.videoId;
g.SH()&&g.PH("yt-remote-session-video-id",a)},this)},a8=function(a){c7("conn",a)},SFa=function(a,b){return new X6($6(a.sa,"/bc"),b)},b8=function(a,b){a.V("proxyStateChange",b)},TFa=function(a){a.D=g.yE((0,g.A)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.AE(a.D);
a.D=NaN},d8=function(a){g.AE(a.R);
a.R=NaN},UFa=function(a){e8(a);
a.L=g.yE((0,g.A)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.AE(a.L);
a.L=NaN},WFa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&isNaN(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Z()&&a.rb.reset(),b8(a,1),f8(a,"getNowPlaying"),VFa(a)):a.F(1)},XFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.rb.videoId&&(g.hc(b.params)?a.rb.o=null:a.rb.o=b.params,a.V("remotePlayerChange"))},YFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.rb.listId=b.params.listId||a.rb.listId;Q7(a.rb,c,d);a.V("remoteQueueChange")},$Fa=function(a,b){b.params=b.params||{};
YFa(a,b);ZFa(a,b);a.V("autoplayDismissed")},ZFa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
O7(a.rb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.rb.playerState&&(c=-1E3);a.rb.playerState=c;c=Number(b.params.loadedTime);a.rb.J=isNaN(c)?0:c;c=Number(b.params.duration);a.rb.H=isNaN(c)?0:c;c=a.rb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=isNaN(d)?!1:!0;c=a.rb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.A=isNaN(e)?0:e;1==a.rb.playerState?UFa(a):e8(a);a.V("remotePlayerChange")},aGa=function(a,b){if(-1E3!=
a.rb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.rb.playerState=c;c=parseInt(b.params.currentTime,10);O7(a.rb,isNaN(c)?0:c);a.V("remotePlayerChange")}},bGa=function(a,b){var c="true"==b.params.muted;
a.rb.volume=parseInt(b.params.volume,10);a.rb.muted=c;a.V("remotePlayerChange")},cGa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},dGa=function(a,b){var c="true"==b.params.hasNext;
a.rb.kg="true"==b.params.hasPrevious;a.rb.hasNext=c;a.V("previousNextChange")},VFa=function(a){g.AE(a.K);
a.K=g.yE((0,g.A)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.Ng(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.td=a;this.A=[];this.A.push(this.td.$_s("screenChange",(0,g.A)(this.RY,this)));this.A.push(this.td.$_s("onlineScreenChange",(0,g.A)(this.UU,this)))},iGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.qE("MDX_CONFIG")||b;mEa();q6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),uEa()&&(h8.o="/api/loungedev"));i8||(i8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ca("yt.mdx.remote.deferredProxies_",i8,void 0));eGa();var c=j8();if(!c){var d=new p7(h8);g.Ca("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);JFa(a,d,function(a){a?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ca("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.Ng(b)),m8.push(g.FE("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),m8.push(g.FE("yt-remote-cast2-receiver-selected",function(){n8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.FE("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.FE("yt-remote-cast2-session-change",fGa)),m8.push(g.FE("yt-remote-connection-change",function(a){a?K7(k8(),"YouTube TV"):o8()||(K7(null,null),MFa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.TE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.Ng(a)),gGa(a),c.start(),k8()||hGa())},kGa=function(){var a=jGa();
H7()&&g.QH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},jGa=function(){var a=j8().td.$_gos();
var b=q8();b&&r8()&&(l6(a,b)||a.push(b));return lEa(a)},s8=function(){var a=lGa();
!a&&H7()&&LFa()&&(a={key:"cast-selector-receiver",name:LFa()});return a},lGa=function(){var a=jGa(),b=q8();
b||(b=o8());return g.Qa(a,function(a){return b&&h6(b,a.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().Ke();return m6(b,a)},fGa=function(a){l8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.x("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.x("yt.mdx.remote.currentScreenId_")},mGa=function(a){g.Ca("yt.mdx.remote.currentScreenId_",a,void 0)},nGa=function(){return g.x("yt.mdx.remote.connectData_")},n8=function(a){g.Ca("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.x("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||mGa("");g.Ca("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.C)(i8,function(b){b(a)}),i8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},o8=function(){var a=g.SH();
if(!a)return null;var b=j8().Ke();return m6(b,a)},u8=function(a,b){q8()&&q8();
mGa(a.id);var c=new $7(h8,a,p8());c.connect(b,nGa());c.subscribe("beforeDisconnect",function(a){e6("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},hGa=function(){var a=o8();
a?(l8("Resume connection to: "+i6(a)),u8(a,0)):(r6(),MFa(),l8("Skipping connecting because no session screen found."))},eGa=function(){var a=p8();
if(g.hc(a)){a=p6();var b=g.QH("yt-remote-session-name")||"",c=g.QH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ca("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},gGa=function(a){a?(g.PH("yt-remote-session-app",a.app),g.PH("yt-remote-session-name",a.name)):(g.RH("yt-remote-session-app"),g.RH("yt-remote-session-name"));
g.Ca("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.J.call(this);
this.D=a;this.A=b;this.B=new g.AG(this);g.K(this,this.B);this.B.O(b,"onCaptionsTrackListChanged",this.pU);this.B.O(b,"captionschanged",this.VS);this.B.O(b,"captionssettingschanged",this.AH);this.B.O(b,"videoplayerreset",this.ir);this.B.O(b,"mdxautoplaycancel",this.gL);this.T=this.B.O(b,"onVolumeChange",this.FF);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.VF,this);c.subscribe("remotePlayerChange",this.Zn,this);c.subscribe("remoteQueueChange",this.ir,this);c.subscribe("autoplayUpNext",this.rF,
this);c.subscribe("previousNextChange",this.SF,this);c.subscribe("nowAutoplaying",this.KF,this);c.subscribe("autoplayDismissed",this.qF,this);this.suggestion=null;this.J=new g.mQ(64);this.C=new g.U(this.xH,500,this);g.K(this,this.C);this.F=new g.U(this.yH,1E3,this);g.K(this,this.F);this.L=new x6(this.uY,0,this);g.K(this,this.L);this.G={};this.R=new g.U(this.YH,1E3,this);g.K(this,this.R);this.K=new g.Fl(this.QQ,1E3,this);g.K(this,this.K);this.N=g.z;this.AH();this.ir();this.Zn()},z8=function(a,b){a.D.Ve(b,
a.A.getVideoData().lengthSeconds)},oGa=function(a){z8(a,0);
a.C.stop();A8(a,new g.mQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.oh()},g.pc(c,b));a.o.lH(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.wg();
if(c){var d=c.Je();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.wk;f=dEa(f);var n=U7(c);l=l||0;var p={videoId:k,currentIndex:l};Q7(n,k,l);g.za(b)&&(O7(n,b),p.currentTime=b);g.za(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Ng(f));Y7(c,"setPlaylist",p);e||W7(c,n);A8(a,new g.mQ(1))},pGa=function(a,b){if(b){var c=a.A.oc("captions","tracklist",{O6:1});
c&&c.length?(a.A.jd("captions","track",b),a.H=!1):(a.A.Mk("captions"),a.H=!0)}else a.A.jd("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.sQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.EU(a.A,d);a.J=b;qGa(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
M:"ytp-remote",P:[{I:"div",M:"ytp-remote-display-status",P:[{I:"div",M:"ytp-remote-display-status-icon",P:[g.Dsa()]},{I:"div",M:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.B=new g.wV(this,250);g.K(this,this.B);this.C=a;this.O(a,"presentingplayerstatechange",this.D);rGa(this,g.AU(a))},rGa=function(a,b){if(3==a.C.Ta()){var c={RECEIVER_NAME:a.C.oc("remote","currentReceiver").name};
c=g.X(b,128)?g.oV("Error a $RECEIVER_NAME",c):b.vb()||g.X(b,4)?g.oV("S'est\u00e0 reproduint a $RECEIVER_NAME",c):g.oV("Connectat a $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.NW.call(this,"Reprodueix a",0,a,b);
this.B=a;this.J={};this.O(a,"onMdxReceiversChange",this.L);this.O(a,"presentingplayerstatechange",this.L);this.L()},G8=function(a){g.ZU.call(this,a);
this.A={key:k6(),name:"Aquest ordinador"};this.C=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.B=this.A;this.Jn=new g.mQ(64);this.J=0;this.H=-1;if(!g.mN(g.Y(this.player))){a=this.player;var b=g.bQ(a);b&&(b=b.Ln())&&(b=new F8(a,b),g.K(this,b));b=new E8(a);g.K(this,b);g.QU(a,b.element,4)}},qGa=function(a,b,c){a.Jn=c;
a.player.V("presentingplayerstatechange",new g.xQ(c,b))},H8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)t8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.wg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ga(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.wk,index:Math.max(a.player.aE(),0),currentTime:0==f?void 0:f};(d=dEa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.Ng(b));"cast-selector-receiver"==b.key?(n8(d||null),I7()?F7().setLaunchParams(d||
null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?e6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().Ke(),(d=m6(d,b.key))&&u8(d,1))}},GEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},sGa={},hEa={p_:"atp",W4:"ska",o4:"que",B3:"mus",S4:"sus",G1:"dsp",E4:"seq"};
f6.prototype.Gh=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var s6,o6="",w6=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",yEa=t6("loadCastFramework")||t6("loadCastApplicationFramework"),IFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(x6,g.J);g.h=x6.prototype;g.h.fM=function(a){this.C=arguments;this.o=!1;this.Ia?this.B=(0,g.H)()+this.Ld:this.Ia=g.Ig(this.D,this.Ld)};
g.h.stop=function(){this.Ia&&(g.Jg(this.Ia),this.Ia=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.W=function(){this.stop();x6.ga.W.call(this)};
g.h.gM=function(){this.B?(this.Ia=g.Ig(this.D,this.B-(0,g.H)()),this.B=null):(this.Ia=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Yi=null;g.h.Sf=!1;g.h.Hl=null;g.h.bz=null;g.h.ll=null;g.h.jk=null;g.h.Rh=null;g.h.wi=null;g.h.yj=null;g.h.bd=null;g.h.xo=0;g.h.Uf=null;g.h.Es=null;g.h.Sh=null;g.h.Um=-1;g.h.TG=!0;g.h.Ii=!1;g.h.Xu=0;g.h.Cr=null;var EEa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.rX=function(a){a=a.target;var b=this.Cr;b&&3==g.Qx(a)?b.Qm():this.gI(a)};
g.h.gI=function(a){try{if(a==this.bd)a:{var b=g.Qx(this.bd),c=this.bd.A,d=this.bd.getStatus();if(g.Sd&&!g.Dc(10)||g.Ud&&!g.Cc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.xf&&!g.Ux(this.bd))break a;this.Ii||4!=b||7==c||(8==c||0>=d?this.o.Mf(3):this.o.Mf(2));J6(this);var e=this.bd.getStatus();this.Um=e;var f=g.Ux(this.bd);(this.Sf=200==e)?(4==b&&F6(this),this.D?(FEa(this,b,f),g.xf&&this.Sf&&3==b&&(this.Y.X(this.A,"tick",this.mX),this.A.start())):E6(this,f),this.Sf&&!this.Ii&&(4==b?this.o.fr(this):
(this.Sf=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Sh=3,D6(13)):(this.Sh=0,D6(14)),F6(this),G6(this))}}catch(k){this.bd&&g.Ux(this.bd)}finally{}};
g.h.mX=function(){var a=g.Qx(this.bd),b=g.Ux(this.bd);this.xo<b.length&&(J6(this),FEa(this,a,b),this.Sf&&4!=a&&B6(this))};
g.h.xW=function(a){I6((0,g.A)(this.wW,this,a),0)};
g.h.wW=function(a){this.Ii||(J6(this),E6(this,a),B6(this))};
g.h.dG=function(a){I6((0,g.A)(this.vW,this,a),0)};
g.h.vW=function(a){this.Ii||(F6(this),this.Sf=a,this.o.fr(this),this.o.Mf(4))};
g.h.cancel=function(){this.Ii=!0;F6(this)};
g.h.NW=function(){this.Hl=null;var a=(0,g.H)();0<=a-this.bz?(2!=this.jk&&this.o.Mf(3),F6(this),this.Sh=2,D6(18),G6(this)):IEa(this,this.bz-a)};g.h=LEa.prototype;g.h.Vu=null;g.h.Re=null;g.h.Dr=!1;g.h.yC=null;g.h.Dp=null;g.h.gw=null;g.h.Wu=null;g.h.nf=null;g.h.ih=-1;g.h.Tm=null;g.h.Zl=null;g.h.connect=function(a){this.Wu=a;a=L6(this.o,null,this.Wu);D6(3);this.yC=(0,g.H)();var b=this.o.H;null!=b?(this.Tm=b[0],(this.Zl=b[1])?(this.nf=1,MEa(this)):(this.nf=2,N6(this))):(d6(a,"MODE","init"),this.Re=new z6(this,void 0,void 0,void 0),this.Re.Yi=this.Vu,A6(this.Re,a,!1,null,!0),this.nf=0)};
g.h.hL=function(a){if(a)this.nf=2,N6(this);else{D6(4);var b=this.o;b.gg=b.Fh.ih;U6(b,9)}a&&this.Mf(2)};
g.h.qu=function(a){return this.o.qu(a)};
g.h.abort=function(){this.Re&&(this.Re.cancel(),this.Re=null);this.ih=-1};
g.h.xC=function(){return!1};
g.h.WF=function(a,b){this.ih=a.Um;if(0==this.nf)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.gg=this.ih;U6(c,2);return}this.Tm=c[0];this.Zl=c[1]}else c=this.o,c.gg=this.ih,U6(c,2);else if(2==this.nf)if(this.Dr)D6(7),this.gw=(0,g.H)();else if("11111"==b){if(D6(6),this.Dr=!0,this.Dp=(0,g.H)(),c=this.Dp-this.yC,!g.Sd||g.Dc(10)||500>c)this.ih=200,this.Re.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.Dp=this.gw=(0,g.H)(),this.Dr=!1};
g.h.fr=function(){this.ih=this.Re.Um;if(this.Re.Sf)0==this.nf?this.Zl?(this.nf=1,MEa(this)):(this.nf=2,N6(this)):2==this.nf&&((!g.Sd||g.Dc(10)?!this.Dr:200>this.gw-this.Dp)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.nf?D6(9):2==this.nf&&D6(10);var a=this.o;a.gg=this.ih;U6(a,2)}};
g.h.oo=function(){return this.o.oo()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Mf=function(a){this.o.Mf(a)};g.h=O6.prototype;g.h.ym=null;g.h.se=null;g.h.Ec=null;g.h.Uu=null;g.h.Fp=null;g.h.QA=null;g.h.Sp=null;g.h.Tn=0;g.h.lS=0;g.h.Kd=null;g.h.Lh=null;g.h.Sg=null;g.h.Ni=null;g.h.Fh=null;g.h.Bs=null;g.h.Fk=-1;g.h.oD=-1;g.h.gg=-1;g.h.bk=0;g.h.Tj=0;g.h.Li=8;var V6=new g.Wf;g.B(OEa,g.vf);g.B(PEa,g.vf);g.B(QEa,g.vf);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.Uu=b;this.ym=c||{};d&&g.za(e)&&(this.ym.OSID=d,this.ym.OAID=e);this.F?(I6((0,g.A)(this.jB,this,a),100),UEa(this)):this.jB(a)};
g.h.jB=function(a){this.Fh=new LEa(this);this.Fh.Vu=null;this.Fh.A=this.D;this.Fh.connect(a)};
g.h.xC=function(){return 0==this.o};
g.h.cG=function(a){this.Lh=null;XEa(this,a)};
g.h.bG=function(){this.Sg=null;this.Ec=new z6(this,this.B,"rpc",this.G);this.Ec.Yi=null;this.Ec.Xu=0;var a=this.QA.clone();g.ln(a,"RID","rpc");g.ln(a,"SID",this.B);g.ln(a,"CI",this.Bs?"0":"1");g.ln(a,"AID",this.Fk);P6(this,a);if(!g.Sd||g.Dc(10))g.ln(a,"TYPE","xmlhttp"),A6(this.Ec,a,!0,this.Sp,!1);else{g.ln(a,"TYPE","html");var b=this.Ec,c=!!this.Sp;b.jk=3;b.Rh=c6(a.clone());HEa(b,c)}};
g.h.WF=function(a,b){if(0!=this.o&&(this.Ec==a||this.se==a))if(this.gg=a.Um,this.se==a&&3==this.o)if(7<this.Li){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Fa(c)&&3==c.length)if(0==c[0])a:{if(!this.Sg){if(this.Ec)if(this.Ec.ll+3E3<this.se.ll)R6(this),this.Ec.cancel(),this.Ec=null;else break a;T6(this);D6(19)}}else this.oD=c[1],0<this.oD-this.Fk&&37500>c[2]&&this.Bs&&0==this.Tj&&!this.Ni&&(this.Ni=I6((0,g.A)(this.PS,this),6E3));else U6(this,11)}else b!=sGa.t0.o&&U6(this,11);else if(this.Ec==a&&
R6(this),!g.E(b)){c=this.D.parse(b);g.Fa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Fk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Sp=e[2],e=e[3],null!=e?this.Li=e:this.Li=6,this.o=3,this.Kd&&this.Kd.dB(),this.QA=L6(this,this.oo()?this.Sp:null,this.Uu),YEa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Kd&&this.Kd.cB(e),this.Tj=0)}}};
g.h.PS=function(){null!=this.Ni&&(this.Ni=null,this.Ec.cancel(),this.Ec=null,T6(this),D6(20))};
g.h.fr=function(a){if(this.Ec==a){R6(this);this.Ec=null;var b=2}else if(this.se==a)this.se=null,b=1;else return;this.gg=a.Um;if(0!=this.o)if(a.Sf)1==b?(b=(0,g.H)()-a.ll,V6.dispatchEvent(new PEa(V6,a.yj?a.yj.length:0,b,this.bk)),Q6(this),this.C.length=0):YEa(this);else{var c=a.Sh,d;if(!(d=3==c||7==c||0==c&&0<this.gg)){if(d=1==b)this.se||this.Lh||1==this.o||2<=this.bk?d=!1:(this.Lh=I6((0,g.A)(this.cG,this,a),ZEa(this,this.bk)),this.bk++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,5);
break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.FL=function(a){if(!g.Ua(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.kY=function(a){a?D6(2):(D6(1),$Ea(this,8))};
g.h.qu=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Kx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Kd&&this.Kd.isActive(this)};
g.h.Mf=function(a){V6.dispatchEvent(new QEa(V6,a))};
g.h.oo=function(){return!(!g.Sd||g.Dc(10))};
g.h=aFa.prototype;g.h.dB=function(){};
g.h.cB=function(){};
g.h.bB=function(){};
g.h.cu=function(){};
g.h.cC=function(){return{}};
g.h.isActive=function(){return!0};g.B(W6,g.J);g.h=W6.prototype;g.h.nW=function(){this.Ld=Math.min(3E5,2*this.Ld);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Ld+15E3*Math.random();g.Ju(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Ld=5E3};g.B(X6,aFa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Lk=function(a){return this.B.Zi(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.Eb||(this.Eb=!0,g.tf(this.B),dFa(this),g.tf(this.A),this.A=null)};
g.h.la=function(){return this.Eb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.Kd=null);d.Kd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.Fk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.pc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&VEa(this.o,c)};
g.h.dB=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)VEa(this.o,a[b])}this.V("handlerOpened")};
g.h.bB=function(a){var b=2==a&&401==this.o.gg;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.cu=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.cC=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.pc(a,this.D);return a};
g.h.cB=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),TEa(this.o)):this.V("handlerMessage",new bFa(a[0],a[1]))};
g.h.NY=function(){this.A.isActive();var a=this.o,b=0;a.Ec&&b++;a.se&&b++;0!=b||this.connect(this.D,this.C)};Z6.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var lFa=(0,g.H)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.B(g7,g.V);g7.prototype.Ke=function(){return this.o};
g7.prototype.contains=function(a){return!!l6(this.o,a)};
g7.prototype.get=function(a){return a?m6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.B(h7,g.V);var tGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ia)&&this.kI()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ia)||(g.AE(this.Ia),this.Ia=NaN)};
g.h.W=function(){this.stop();h7.ga.W.call(this)};
g.h.kI=function(){this.Ia=NaN;this.o=g.jF($6(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.PY,this),onError:(0,g.A)(this.OY,this),Pd:(0,g.A)(this.QY,this)})};
g.h.PY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new g6(c))};
g.h.OY=function(a){this.o=null;a.status&&404==a.status?this.A>=tGa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=tGa[this.A],this.Ia=g.yE((0,g.A)(this.kI,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.QY=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.V("screenChange");!g.QH("yt-remote-lounge-token-expiration")&&pFa(this);g.AE(this.A);this.A=g.yE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);mFa(this,a);k7(this,!1);this.V("screenChange");b(a);a.token||pFa(this)};
g.h.remove=function(a,b){var c=i7(this);oFa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.xs=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.W=function(){g.AE(this.A);j7.ga.W.call(this)};
g.h.uM=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.tM=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.B(m7,g.V);g.h=m7.prototype;g.h.start=function(){var a=parseInt(g.QH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?o7(this):(this.C=(0,g.H)()+3E5,g.PH("yt-remote-fast-check-period",this.C),this.Xx())};
g.h.isEmpty=function(){return g.hc(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Sb(this.o,function(b,d){return b&&!!m6(a,d)},this);
n7(this,b)};
g.h.W=function(){g.AE(this.B);this.B=NaN;this.A&&(this.A.abort(),this.A=null);m7.ga.W.call(this)};
g.h.Xx=function(){g.AE(this.B);this.B=NaN;this.A&&this.A.abort();var a=sFa(this);if(g.Wb(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.bc(a).join(",")},(0,g.A)(this.VV,this,a),(0,g.A)(this.UV,this))}else n7(this,{}),o7(this)};
g.h.VV=function(a,b){this.A=null;var c=g.bc(sFa(this));if(g.qb(c,g.bc(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.yc("Changing Screen set during request."),this.Xx()};
g.h.UV=function(a){this.yc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.yc=function(a){c7("OnlineScreenService",a)};g.B(p7,g7);g.h=p7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.xs=function(a,b,c,d){this.B.contains(a)?this.B.xs(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.Ke=function(a){return a?this.o:g.bb(this.o,(0,g.fe)(this.C,function(a){return!this.contains(a)},this))};
g.h.lI=function(){return(0,g.fe)(this.Ke(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.mI=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.tf(f);d(q7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.tf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.SY=function(a,b,c,d){g.jF($6(this.F,"/pairing/get_screen"),{method:"POST",Tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new g6(d.screen||{});if(!e.name||wFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);wFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(q7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Pd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.tf(this.B);g.tf(this.A);p7.ga.W.call(this)};
g.h.HM=function(){xFa(this);this.V("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.B(s7,g.V);g.h=s7.prototype;g.h.gr=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Qe=function(a){this.la()||(a&&t7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){c7(this.R,a)};
g.h.oI=function(){return null};
g.h.ly=function(a){var b=this.A;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.ly("");s7.ga.W.call(this)};g.B(u7,s7);g.h=u7.prototype;g.h.ky=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);zFa(this)};
g.h.Hk=function(a){this.info("launchWithParams no-op for Cast: "+g.Ng(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.Qe()},this),(0,g.A)(function(){this.Qe(Error("Failed to stop receiver app."))},this)):this.Qe(Error("Stopping cast device witout session."))};
g.h.ly=g.z;g.h.W=function(){this.info("disposeInternal");g.AE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.ga.W.call(this)};
g.h.ZW=function(a,b){if(!this.la())if(b){var c=g.Fx(b);if(g.Ia(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ng(c));switch(d){case "mdxSessionStatus":yFa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.nC=function(a,b,c,d){vFa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.yE((0,g.A)(this.nC,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.oI=function(){return this.o};
g.h.TY=function(a){this.la()||a||(t7(this,"Cast session died."),this.Qe())};g.B(v7,s7);g.h=v7.prototype;g.h.ky=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.Hk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.AE(this.F);this.C?this.C.stop((0,g.A)(this.Qe,this,null),(0,g.A)(this.Qe,this,"Failed to stop DIAL device.")):this.Qe()};
g.h.W=function(){this.o();this.o=g.z;g.AE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;v7.ga.W.call(this)};
g.h.WY=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.z,this.Qe())};
g.h.Iv=function(a){this.K=k6();if(this.D){var b=new chrome.cast.DialLaunchResponse(!0,BFa(this));a(b);AFa(this)}else this.G=(0,g.A)(function(){g.AE(this.F);this.G=g.z;this.F=NaN;var b=new chrome.cast.DialLaunchResponse(!0,BFa(this));a(b);AFa(this)},this),this.F=g.yE((0,g.A)(function(){this.G()},this),100)};
g.h.UN=function(a,b,c){vFa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.gr(a),b(new chrome.cast.DialLaunchResponse(!1))):this.Iv(b,c)},this),(0,g.A)(function(a){t7(this,"Failed to get DIAL screen: "+a);
this.Iv(b,c)},this))};g.B(w7,s7);w7.prototype.stop=function(){this.Qe()};
w7.prototype.ky=g.z;w7.prototype.Hk=function(){g.AE(this.o);this.o=NaN;var a=m6(this.J.Ke(),this.A.label);a?this.gr(a):this.Qe(Error("No such screen"))};
w7.prototype.W=function(){g.AE(this.o);this.o=NaN;w7.ga.W.call(this)};g.B(x7,g.V);g.h=x7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.A)(this.YF,this),(0,g.A)(this.CV,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.yT,this);chrome.cast.initialize(c,(0,g.A)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.C),iFa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.nI,this)),this.B=DFa(this),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.yc("Failed to set initial custom receivers: "+g.Ng(a))},this)),this.V("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.A)(function(a){this.yc("Failed to initialize API: "+g.Ng(a));
b(!1)},this))};
g.h.SX=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=m6(this.A.Ke(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=CFa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(d),chrome.cast.setCustomReceivers(this.B,
g.z,(0,g.A)(function(a){this.yc("Failed to set initial custom receivers: "+g.Ng(a))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.ly(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.TX=function(a){this.la()?this.yc("Setting connection data on disposed cast v2"):this.o?this.o.Hk(a):this.yc("Setting connection data without a session")};
g.h.VY=function(){this.la()?this.yc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.YF,this),(0,g.A)(this.ZV,this))};
g.h.W=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.nI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);g.Za(g.x("yt.mdx.remote.debug.handlers_")||[],fFa);g.tf(this.o);x7.ga.W.call(this)};
g.h.yc=function(a){c7("Controller",a)};
g.h.ZF=function(a,b){this.o==a&&(b||A7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.yV=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.yc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.yc("Stopping receiver w/o session: "+a.friendlyName)}else this.yc("onReceiverAction_ called without receiver.")};
g.h.yT=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.yc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.yc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.B)return y7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.yc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.UN,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.A)(b.Iv,b))};
g.h.YF=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.yc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=m6(this.A.Ke(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.tf(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.ZF,this,this.o)),this.o.Hk(null));this.o.ky(a)}}};
g.h.UY=function(){return this.o?this.o.oI():null};
g.h.ZV=function(a){this.la()||(this.yc("Failed to estabilish a session: "+g.Ng(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.CV=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.V("yt-remote-cast2-availability-change",z7(this))}};
g.h.nI=function(){this.la()||(this.B=DFa(this),y7("Updating custom receivers: "+g.Ng(this.B)),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.yc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.TX;x7.prototype.setConnectedScreenStatus=x7.prototype.SX;x7.prototype.stopSession=x7.prototype.VY;x7.prototype.getCastSession=x7.prototype.UY;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.kg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!isNaN(this.B))};
g.h.vb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.B(T7,g.V);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.V("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.V("remotePlayerChange")):V7(this,this.pause)};
g.h.jI=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.vb()||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.V("remotePlayerChange")}else V7(this,g.La(this.jI,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.V("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.yc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.yc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.La(this.setVolume,a,b))};
g.h.lH=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ng(b.style),g.pc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.La(this.lH,a,b))};
g.h.wz=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pb.id});var c=U7(this);c.audioTrackId=b.Pb.id;W7(this,c)}else V7(this,g.La(this.wz,a,b))};
g.h.rr=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.La(this.rr,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.La(this.nextVideo,a,b))};
g.h.DB=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.DB)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}T7.ga.dispose.call(this)};
g.h.W=function(){QFa(this);this.C=null;this.D.clear();S7(this,null);T7.ga.W.call(this)};
g.h.xz=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.YC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.uV=function(a,b){this.V(a,b)};
g.h.XS=function(a){if(!a)this.Wn(null),S7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.Wn=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),RFa(this),this.V("remotePlayerChange")};
g.h.WS=function(a){a?(RFa(this),this.V("remotePlayerChange")):this.Wn(null)};
g.h.Dy=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.jT=function(){var a=NFa();a&&S7(this,a)};
g.h.yc=function(a){c7("CP",a)};g.B($7,g.V);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.za(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.za(k)&&(l.currentIndex=k);c&&(this.rb.listId=c);this.rb.videoId=d;this.rb.index=k||0;this.rb.state=3;O7(this.rb,m);this.C="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.Ng(l));this.o.connect({method:"setPlaylist",
params:g.Ng(l)},a,pEa())}else a8("Connecting without params"),this.o.connect({},a,pEa());TFa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),b8(this,3));$7.ga.dispose.call(this)};
g.h.W=function(){c8(this);e8(this);d8(this);g.AE(this.J);this.J=NaN;g.AE(this.K);this.K=NaN;this.B=null;g.mG(this.T);this.T.length=0;this.o.dispose();$7.ga.W.call(this);this.C=this.G=this.A=this.rb=this.o=null};
g.h.kM=function(){this.F(2)};
g.h.bT=function(){a8("Channel opened");this.N&&(this.N=!1,d8(this),this.R=g.yE((0,g.A)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
tEa(cFa(this.o),this.aa)};
g.h.YS=function(){a8("Channel closed");isNaN(this.D)?r6(!0):r6();this.dispose()};
g.h.ZS=function(a){r6();isNaN(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.aT=function(a){a.params?a8("Received: action="+a.action+", params="+g.Ng(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Fx(a.params.devices);this.A=(0,g.I)(a,function(a){return new f6(a)});
a=!!g.Qa(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
WFa(this,a);break;case "loungeScreenDisconnected":g.$a(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
WFa(this,!1);break;case "remoteConnected":var b=new f6(g.Fx(a.params.device));g.Qa(this.A,function(a){return b?a.id==b.id:!1})||g.Xa(this.A,b);
break;case "remoteDisconnected":b=new f6(g.Fx(a.params.device));g.$a(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":YFa(this,a);break;case "nowPlaying":$Fa(this,a);break;case "onStateChange":ZFa(this,a);break;case "onAdStateChange":aGa(this,a);break;case "onVolumeChanged":bGa(this,a);break;case "onSubtitlesTrackChanged":XFa(this,a);break;case "nowAutoplaying":cGa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":dGa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.zX=function(){if(this.B){var a=this.B;this.B=null;this.rb.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.Lk;$7.prototype.ha=function(){var a=3;this.la()||(a=0,isNaN(this.H())?Y6(this.o)&&isNaN(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ha;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.V("beforeDisconnect",a);1==a&&r6();dFa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.fa=function(){var a=this.rb;this.B&&(a=this.rb.clone(),Q7(a,this.B,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.fa;
$7.prototype.ma=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.rb.videoId&&(this.B=b.videoId,g.AE(this.J),this.J=g.yE((0,g.A)(this.zX,this),5E3));var c=[];this.rb.listId==b.listId&&this.rb.videoId==b.videoId&&this.rb.index==b.index||c.push("remoteQueueChange");this.rb.playerState==b.playerState&&this.rb.volume==b.volume&&this.rb.muted==b.muted&&P7(this.rb)==P7(b)&&g.Ng(this.rb.o)==g.Ng(b.o)||c.push("remotePlayerChange");this.rb.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Z=function(){var a=this.o.F.id,b=g.Qa(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Z;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.ea=function(){return this.C||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.ea;$7.prototype.da=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.da;$7.prototype.xa=function(){if(!isNaN(this.H())){var a=this.o.A;g.Ku(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.xa;$7.prototype.ka=function(a,b){f8(this,a,b);VFa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.B(g8,g7);g.h=g8.prototype;g.h.Ke=function(a){return this.td.$_gs(a)};
g.h.contains=function(a){return!!this.td.$_c(a)};
g.h.get=function(a){return this.td.$_g(a)};
g.h.start=function(){this.td.$_st()};
g.h.add=function(a,b,c){this.td.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.td.$_r(a,b,c)};
g.h.xs=function(a,b,c,d){this.td.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.A.length;a<b;++a)this.td.$_ubk(this.A[a]);this.A.length=0;this.td=null;g8.ga.W.call(this)};
g.h.RY=function(){this.V("screenChange")};
g.h.UU=function(){this.V("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.SY;p7.prototype.$_gsppc=p7.prototype.mI;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.xs;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.Ke;p7.prototype.$_gos=p7.prototype.lI;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.Lk;var h8=null,i8=null,x8=null,m8=[];g.r(y8,g.J);g.h=y8.prototype;
g.h.W=function(){g.J.prototype.W.call(this);this.C.stop();this.F.stop();this.L.stop();this.N();this.o.unsubscribe("proxyStateChange",this.VF,this);this.o.unsubscribe("remotePlayerChange",this.Zn,this);this.o.unsubscribe("remoteQueueChange",this.ir,this);this.o.unsubscribe("autoplayUpNext",this.rF,this);this.o.unsubscribe("previousNextChange",this.SF,this);this.o.unsubscribe("nowAutoplaying",this.KF,this);this.o.unsubscribe("autoplayDismissed",this.qF,this);this.o=this.D=null};
g.h.sE=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).vb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Qm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.wz(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.wz(this.A.getVideoData(1).videoId,c)}};
g.h.VS=function(a){this.L.fM(a)};
g.h.uY=function(a){this.sE("control_subtitles_set_track",g.hc(a)?null:a)};
g.h.AH=function(){var a=this.A.oc("captions","track");g.hc(a)||C8(this,a)};
g.h.FF=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.Zn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.R.start();this.o.subscribe("remotePlayerChange",this.Zn,this)}};
g.h.pU=function(){g.hc(this.G)||pGa(this,this.G);this.H=!1};
g.h.VF=function(a,b){this.F.stop();2==b&&this.yH()};
g.h.Zn=function(){if(B8(this)){this.C.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.ql(1);break;case 1082:case 1083:this.D.ql(0);break;default:this.D.ql(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.mQ(8));this.xH();break;case 1085:case 3:A8(this,new g.mQ(9));break;case 1083:case 0:A8(this,new g.mQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.mQ(4));break;case 2:A8(this,new g.mQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.mQ(64));break;case -1E3:A8(this,new g.mQ(128,{errorCode:"mdx.remoteerror",message:"Aquest v\u00eddeo no es pot reproduir de manera remota."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,pGa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.R.isActive()||this.YH()}else oGa(this)};
g.h.SF=function(){this.A.V("mdxpreviousnextchange")};
g.h.ir=function(){B8(this)||oGa(this)};
g.h.gL=function(){this.o.DB()};
g.h.rF=function(a){a&&(a=g.jF("/watch_queue_ajax",{method:"GET",nd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.zW,this)}))&&(this.N=(0,g.A)(a.abort,a))};
g.h.zW=function(a,b){var c=new g.gP(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.KF=function(a){isNaN(a)||this.A.V("mdxnowautoplaying",a)};
g.h.qF=function(){this.A.V("mdxautoplaycanceled")};
g.h.QQ=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.jI(a)};
g.h.YH=function(){if(B8(this)){var a=U7(this.o);this.B.La(this.T);a.muted?this.A.mute():this.A.xg();this.A.setVolume(a.volume);this.T=this.B.O(this.A,"onVolumeChange",this.FF)}};
g.h.xH=function(){this.C.stop();if(!this.o.la()){var a=U7(this.o);a.vb()&&A8(this,new g.mQ(8));z8(this,P7(a));this.C.start()}};
g.h.yH=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.F.start()};g.r(E8,g.W);E8.prototype.D=function(a){rGa(this,a.state)};g.r(F8,g.NW);F8.prototype.L=function(){var a=this.B.oc("remote","receivers");a&&1<a.length&&!this.B.oc("remote","quickCast")?(this.J=g.sb(a,this.F,this),g.OW(this,(0,g.I)(a,this.F)),a=this.B.oc("remote","currentReceiver"),this.Ag(this.F(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.F=function(a){return a.key};
F8.prototype.uf=function(a){return"cast-selector-receiver"==a?"Emet\u2026":this.J[a].name};
F8.prototype.Nd=function(a){g.NW.prototype.Nd.call(this,a);this.B.jd("remote","currentReceiver",this.J[a]);this.D.Mb()};g.r(G8,g.ZU);g.h=G8.prototype;g.h.create=function(){iGa(g.eN(g.Y(this.player)));this.D.push(g.FE("yt-remote-before-disconnect",this.QS,this));this.D.push(g.FE("yt-remote-connection-change",this.EV,this));this.D.push(g.FE("yt-remote-receiver-availability-change",this.TF,this));this.D.push(g.FE("yt-remote-auto-connect",this.BV,this));this.D.push(g.FE("yt-remote-receiver-resumed",this.AV,this));this.TF()};
g.h.load=function(){this.player.Fw();g.ZU.prototype.load.call(this);this.C=new y8(this,this.player,this.o);var a=(a=nGa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&this.Ve(a);qGa(this,this.Jn,this.Jn);g.t0(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.uf(this.C,this.o);this.o=this.C=null;g.ZU.prototype.unload.call(this);g.t0(this.player.app,5)};
g.h.W=function(){g.GE(this.D);g.ZU.prototype.W.call(this)};
g.h.oi=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.sE.apply(this.C,[a].concat(g.ea(c)))};
g.h.ql=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.aM=function(){return this.loaded?this.C.suggestion:null};
g.h.kg=function(){return this.o?U7(this.o).kg:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.Ve=function(a,b){this.J=a||0;this.player.V("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Sc():!a.isAdPlaying()&&this.player.Sc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+N7(a):a.B,isPeggedToLive:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.C?a.C+
N7(a):a.C}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.rr=function(){this.o&&this.o.rr()};
g.h.QS=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.EV=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.tf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.ZD(a.videoId,P7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.TF=function(){this.F=[this.A].concat(kGa());var a=s8()||this.A;H8(this,a);this.player.Ba("onMdxReceiversChange")};
g.h.BV=function(){var a=s8();H8(this,a)};
g.h.AV=function(){this.B=s8()};
g.h.Oc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&J7(),!0):!1}};
g.h.Dy=function(){this.o.Dy()};
g.h.Ac=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.KZ.remote=G8;})(_yt_player);
