if (typeof(zmsBreadcrumbData) == 'undefined'){
  var zmsBreadcrumbData = Array();
}
zmsBreadcrumbData[3] = {
300:{"name":"騎單車者","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/cyclists_/index.html","target":""}
,303:{"name":"其他道路使用者","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/other_road_users_/index.html","target":""}
,304:{"name":"白綫及行車綫","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/white_lines_and_traffic_lanes_/index.html","target":""}
,305:{"name":"雙白綫","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/double_white_lines_/index.html","target":""}
,306:{"name":"輕鐵行車綫","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/light_rail_lanes_/index.html","target":""}
,307:{"name":"巴士綫","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/bus_lanes_/index.html","target":""}
,308:{"name":"單程路","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/one_way_roads_/index.html","target":""}
,310:{"name":"窄路、斜坡","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/narrow_roads_/index.html","target":""}
,312:{"name":"分隔車路","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/dual_carriageways_/index.html","target":""}
,313:{"name":"車速較高的道路","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/roads_with_faster_traffic_/index.html","target":""}
,314:{"name":"快速公路及主幹路","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/expressways_and_trunk_road_/index.html","target":""}
,315:{"name":"隧道","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/tunnels_/index.html","target":""}
,316:{"name":"路口","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/junctions_/index.html","target":""}
,317:{"name":"交通燈的路口","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/traffic_light_junctions_/index.html","target":""}
,318:{"name":"必須停車或讓路的路口","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/stop_and_give_way_junctions_/index.html","target":""}
,319:{"name":"迴旋處","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/roundabouts_/index.html","target":""}
,320:{"name":"分隔車路的路口","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/junctions_with_dual_carriageway_roads/index.html","target":""}
,322:{"name":"斑馬綫","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/zebra_crossings_/index.html","target":""}
,323:{"name":"綠色人像過路處","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/green_man_crossing_/index.html","target":""}
,325:{"name":"猛烈的陽光、夜間駕駛","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/bright_sunlight_/index.html","target":""}
,327:{"name":"雨、霧、風","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/rain_fog_wind_/index.html","target":""}
,328:{"name":"道路工程","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/road_works_/index.html","target":""}
,329:{"name":"在分隔車路的道路工程","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/road_works_on_dual_carriageways_/index.html","target":""}
,330:{"name":"不准停車的地點","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/where_not_to_stop_/index.html","target":""}
,331:{"name":"禁止泊車的地點","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/where_not_to_park_/index.html","target":""}
,332:{"name":"准許泊車的地點","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/where_to_park_/index.html","target":""}
,333:{"name":"泊車","url":"/tc/road_safety/road_users_code/index/chapter_5_for_all_drivers/parking/index.html","target":""}
,334:{"name":"商用車輛","url":"/tc/road_safety/road_users_code/index/chapter_6_for_professional_drivers/commercial_vehicles_/index.html","target":""}
,335:{"name":"運載貨物、長車和拖車","url":"/tc/road_safety/road_users_code/index/chapter_6_for_professional_drivers/loads_/index.html","target":""}
,338:{"name":"各種限制","url":"/tc/road_safety/road_users_code/index/chapter_6_for_professional_drivers/restrictions_/index.html","target":""}
,339:{"name":"第七章電單車駕駛人須知","url":"/tc/road_safety/road_users_code/index/chapter_7_for_motor_cycles/index.html","target":""}
,340:{"name":"開車前","url":"/tc/road_safety/road_users_code/index/chapter_7_for_motor_cycles/before_you_ride_/index.html","target":""}
,341:{"name":"駕駛時","url":"/tc/road_safety/road_users_code/index/chapter_7_for_motor_cycles/riding_along_/index.html","target":""}
,342:{"name":"行車位置","url":"/tc/road_safety/road_users_code/index/chapter_7_for_motor_cycles/positioning_/index.html","target":""}
,343:{"name":"信號與乘客","url":"/tc/road_safety/road_users_code/index/chapter_7_for_motor_cycles/signals_passengers/index.html","target":""}
,345:{"name":"第八章道路語言","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/index.html","target":""}
,346:{"name":"信號","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/signals_/index.html","target":""}
,347:{"name":"交通燈","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/traffic_lights_/index.html","target":""}
,348:{"name":"指示車輛的交通燈","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/traffic_lights_for_drivers_and_riders/index.html","target":""}
,363:{"name":"隧道區信號燈","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/tunnel_area_and_expressway_signals/index.html","target":""}
,365:{"name":"交通標誌系統","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/the_signing_system_/index.html","target":""}
,366:{"name":"指令標誌","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/signs_giving_orders_/index.html","target":""}
,367:{"name":"指令交通信號","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/traffic_signals_giving_orders_/index.html","target":""}
,368:{"name":"警告標誌","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/signs_giving_warning_/index.html","target":""}
,369:{"name":"臨時標誌","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/temporary_signs_/index.html","target":""}
,370:{"name":"方向標誌","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/direction_signs_/index.html","target":""}
,371:{"name":"提示標誌","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/signs_giving_information_/index.html","target":""}
,372:{"name":"警告及提示道路標記","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/road_markings_giving_warning_and_information_/index.html","target":""}
,373:{"name":"指令道路標記","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/road_markings_giving_orders_/index.html","target":""}
,374:{"name":"主要幹綫號碼","url":"/tc/road_safety/road_users_code/index/chapter_8_the_language_of_the_road/major_road_route_numbers_/index.html","target":""}
,375:{"name":"第九章兒童使用道路","url":"/tc/road_safety/road_users_code/index/chapter_9_your_child_as_a_road_user/index.html","target":""}
,376:{"name":"兒童在路上應注意的事項","url":"/tc/road_safety/road_users_code/index/chapter_9_your_child_as_a_road_user/children_on_the_road_/index.html","target":""}
,377:{"name":"確保兒童乘車安全","url":"/tc/road_safety/road_users_code/index/chapter_9_your_child_as_a_road_user/child_safety_in_cars_/index.html","target":""}
,378:{"name":"第十章緊急事故","url":"/tc/road_safety/road_users_code/index/chapter_10_emergencies/index.html","target":""}
,379:{"name":"中途壞車和其他緊急事故","url":"/tc/road_safety/road_users_code/index/chapter_10_emergencies/breakdown_and_emergencies_/index.html","target":""}
,380:{"name":"警告其他駕駛人 ","url":"/tc/road_safety/road_users_code/index/chapter_10_emergencies/warning_other_drivers/index.html","target":""}
,381:{"name":"發生交通意外","url":"/tc/road_safety/road_users_code/index/chapter_10_emergencies/traffic_accidents/index.html","target":""}
,382:{"name":"遇上緊急事故時","url":"/tc/road_safety/road_users_code/index/chapter_10_emergencies/in_an_emergency_/index.html","target":""}
,383:{"name":"在路上急救","url":"/tc/road_safety/road_users_code/index/chapter_10_emergencies/first_aid_on_the_road_/index.html","target":""}
,385:{"name":"應怎樣做","url":"/tc/road_safety/road_users_code/index/traffic_accidents/what_to_do/index.html","target":""}
,386:{"name":"急救","url":"/tc/road_safety/road_users_code/index/traffic_accidents/first_aid/index.html","target":""}
,387:{"name":"城巴","url":"/tc/transport_in_hong_kong/public_transport/buses/citybus/index.html","target":""}
,388:{"name":"新巴","url":"/tc/transport_in_hong_kong/public_transport/buses/new_world_first_bus/index.html","target":""}
,389:{"name":"九巴","url":"/tc/transport_in_hong_kong/public_transport/buses/kowloon_motor_bus/index.html","target":""}
,390:{"name":"龍運巴士","url":"/tc/transport_in_hong_kong/public_transport/buses/long_win_bus/index.html","target":""}
,391:{"name":"新大嶼山巴士","url":"/tc/transport_in_hong_kong/public_transport/buses/new_lantao_bus/index.html","target":""}
,392:{"name":"行人專用區","url":"/tc/transport_in_hong_kong/pedestrianisation/pedestrianisation/index.html","target":""}
,393:{"name":"半山電梯","url":"/tc/transport_in_hong_kong/pedestrianisation/hillside_escalator/index.html","target":""}

};
